string_input = input()
print(string_input[2])
print(string_input[-2])
print(string_input[:5])
print(string_input[:-2])
print(string_input[::2])
print(string_input[1::2])
print(string_input[::-1])
print(string_input[-2::-2])
print(len(string_input))
