import numpy as np
grades = np.array([[87,96,70],[100,87,90],[94,77,90],[100,81,82]])
print(grades)
meanvalue = grades.mean(axis=0)
print("Meanvalue: ")  #only axis mean value
print(meanvalue)
print("Max value: ")
maxv = grades.max()
print(maxv)
print("Min Value: ")
meanv = grades.min()
print(meanv)
print("summation: ")
summation  = grades.sum()
print(summation)
print("Standard deviation : ")
stdd = grades.std()
print(stdd)
print("Sample Varriance")
svar = grades.var()
print(svar)
print("Mean value total ")
mentotal = grades.mean()
print(mentotal)
print("Mean in axis 1")
axi1 = grades.mean(axis=1)
print(axi1)
print("Max in axis 0 ")
maxaxis0 = grades.max(axis=0)
print(maxaxis0)
print("Max in axis 1: ")
macxinaxis1 = grades.max(axis=1)
print(macxinaxis1)
